// Создание блоков с вакансиями:
const candidatesItems = [
  {
    id: 1,
    direction: "marketing",
    workType: "remote/office",
    speciality: "Digital Marketing Specialist (PR|SMM)",
    location: "Ukraine",
    techLevel: "junior",
  },
  { id: 2, direction: "design", workType: "office", speciality: "Graphic Artist", location: "Poland", techLevel: "middle" },
  { id: 3, direction: "sales", workType: "relocation", speciality: "Sales Manager 1", location: "Bulgaria", techLevel: "senior" },
  {
    id: 4,
    direction: "development",
    workType: "freelance",
    speciality: "PHP Developer",
    location: "USA",
    techLevel: "leader",
  },
  { id: 5, direction: "analytics", workType: "remote/office", speciality: "Analytic 1", location: "Canada", techLevel: "expert" },
  { id: 6, direction: "other", workType: "office", speciality: "QA Engineer", location: "UK", techLevel: "other" },
  {
    id: 7,
    direction: "marketing",
    workType: "relocation",
    speciality: "Digital Marketing Specialist (PR|SMM)",
    location: "Germany",
    techLevel: "junior",
  },
  { id: 8, direction: "design", workType: "freelance", speciality: "Game Designer", location: "Sweden", techLevel: "middle" },
  {
    id: 9,
    direction: "sales",
    workType: "remote/office",
    speciality: "Sales Manager 2",
    location: "Singapore",
    techLevel: "senior",
  },
  { id: 10, direction: "development", workType: "office", speciality: "REACT Developer", location: "Spain", techLevel: "leader" },
  { id: 11, direction: "analytics", workType: "relocation", speciality: "Analytic 2", location: "Ukraine", techLevel: "expert" },
  { id: 12, direction: "other", workType: "freelance", speciality: "Support Manager", location: "Poland", techLevel: "other" },
  {
    id: 13,
    direction: "marketing",
    workType: "remote/office",
    speciality: "Social Media Marketing Manager",
    location: "Bulgaria",
    techLevel: "junior",
  },
  { id: 14, direction: "design", workType: "office", speciality: "UX Designer", location: "USA", techLevel: "middle" },
  { id: 15, direction: "sales", workType: "relocation", speciality: "Sales Manager 3", location: "Canada", techLevel: "senior" },
  {
    id: 16,
    direction: "development",
    workType: "freelance",
    speciality: "Python Developer",
    location: "UK",
    techLevel: "leader",
  },
  {
    id: 17,
    direction: "analytics",
    workType: "remote/office",
    speciality: "Analytic 3",
    location: "Germany",
    techLevel: "expert",
  },
  { id: 18, direction: "other", workType: "office", speciality: "L1 Rust Auditor", location: "Sweden", techLevel: "other" },
  {
    id: 19,
    direction: "marketing",
    workType: "relocation",
    speciality: "SMM Marketing",
    location: "Singapore",
    techLevel: "junior",
  },
  {
    id: 20,
    direction: "design",
    workType: "freelance",
    speciality: "Product Game Designer",
    location: "Spain",
    techLevel: "middle",
  },
];

export default candidatesItems;
